version: '3.7'
services:
  app:
    build: .
    container_name: sma_app
    restart: always
    volumes:
     - .:/app
    environment:
      - DEBUG=false
      - SECRET_KEY='django-insecure-81ph6of)gyz(3*fa1fhpolbt5o)ax74)hlv1e3iud+x84&2l3@'
      - DATABASE_URL=postgres://postgres:postgres@db:5432/postgres
      - ALPHA_VANTAGE_API_KEY=X86NOH6II01P7R24
    depends_on:
     - db
    ports:
     - 8000:8000
  db:
    container_name: sma_db
    image: postgres:12.0-alpine
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - 5432:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data/

volumes:
  postgres_data: